[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = 119.29.29.29,223.5.5.5,system
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = false
block-quic = all

[Proxy Group]
Proxies = select,JP,TW,HK,US,Other,select=0
AI Service = select,JP,US,TW,select=0
Bilibili = select,DIRECT,HK,select=0
Final = select,JP,TW,HK,US,Other,DIRECT,select=0
JP = select,policy-regex-filter=(?i)日本|JP|Japan|🇯🇵,select=0
TW = select,policy-regex-filter=(?i)台|新北|彰化|TW|Taiwan,select=0
HK = select,policy-regex-filter=(?i)港|HK|Hong|Kong|🇭🇰,select=0
US = select,policy-regex-filter=(?i)美|US|United States|🇺🇸,select=0
Other = select,policy-regex-filter=(?i)^(?!.*(港|HK|Hong|Kong|🇭🇰|台|新北|彰化|TW|Taiwan|日本|JP|Japan|🇯🇵|美|US|United States|🇺🇸)).*,select=0

[Rule]
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/banad.list,REJECT
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/private-domain.list,DIRECT
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/private-ip.list,DIRECT,no-resolve
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/steam@cn.list,DIRECT
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/steam.list,Proxies
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/scholar.list,DIRECT
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/bilibili-ip.list,Bilibili,no-resolve
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/bilibili-domain.list,Bilibili
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/ai.list,AI Service
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/telegram-ip.list,Proxies,no-resolve
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/proxy.list,Proxies
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/direct-domain.list,DIRECT
RULE-SET,https://gh-proxy.org/https://github.com/volcano242/volcano/blob/rules-output/list/direct-ip.list,DIRECT,no-resolve
FINAL,Final

[URL Rewrite]
^https?://(www.)?g.cn https://www.google.com 302
^https?://(www.)?google.cn https://www.google.com 302
